In [5]:
import matplotlib.pyplot as plt
import pandas as pd
try:
  import pandas_datareader.data as web
  import statsmodels.api as sm
except:
  !pip install pip pandas-datareader  
  import pandas_datareader.data as web
  !pip install pip statsmodels
  import statsmodels.api as sm

%matplotlib inline

In [6]:
fmodel = web.DataReader('F-F_Research_Data_5_Factors_2x3_daily', 'famafrench', start = "2008-01-30", end = "2020-10-31")

factormodel = pd.DataFrame.from_dict(fmodel[0])

model = web.get_data_yahoo('VTI', start = "2008-01-29", end = "2020-10-31")['Adj Close'].pct_change().dropna()*100


Y = model
X = sm.add_constant(factormodel)

model = sm.OLS(Y, X)
results =model.fit()
#print(results.summary())

model

            Mkt-RF   SMB   HML   RMW   CMA     RF
Date
2008-01-30   -0.59 -0.40 -0.04  0.24  0.11  0.010
2008-01-31    1.66  0.87  0.43  0.40  0.11  0.010
2008-02-01    1.48  0.70  0.07 -0.70 -0.45  0.007
2008-02-04   -0.99  0.05 -0.20 -0.39 -0.10  0.007
2008-02-05   -3.01  0.32  0.07  0.01  0.29  0.007
...            ...   ...   ...   ...   ...    ...
2020-10-26   -1.85 -0.45 -0.40 -0.04  0.05  0.000
2020-10-27   -0.23 -0.58 -2.38 -0.27 -0.73  0.000
2020-10-28   -3.42  0.22  0.55 -0.49  0.01  0.000
2020-10-29    1.13  0.14  0.23  0.23  0.57  0.000
2020-10-30   -1.45 -0.24  1.87  0.25  0.00  0.000

[3213 rows x 6 columns]